In [262]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error
from sklearn.tree import DecisionTreeRegressor

from sklearn.model_selection import train_test_split

In [263]:
titanic  = pd.read_csv("train.csv")

In [264]:
# titanic.isna().sum()

In [265]:
titanic.drop(["Cabin"], axis=1, inplace=True)

In [266]:
titanic.dropna(inplace=True)

In [267]:
cols = ["Pclass", "Sex","Age", "Fare"]
df=titanic[cols]

In [268]:
labelEncoder = LabelEncoder()
df['Sex'] = labelEncoder.fit_transform(df["Sex"])

C:\Users\DELL\AppData\Local\Temp\ipykernel_216\1525719231.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sex'] = labelEncoder.fit_transform(df["Sex"])

In [299]:
df

,Pclass,Sex,Age,Fare,f0x,ri1,f1x,ri2,f2x,ri3,...,ri5,f5x,ri6,f6x,ri7,f7x,ri8,f8x,ri9,f9x
0,3,1,22.0,7.2500,32.117263,-24.867263,9.821490,-2.571490,6.940183,0.309817,...,0.462226,6.955281,0.294719,6.923146,0.326854,6.773355,0.476645,6.830444,0.419556,6.865994
1,1,0,38.0,71.2833,32.117263,39.166037,81.181429,-9.898129,82.291763,-11.008463,...,-10.227859,77.707664,-6.424364,77.675530,-6.392230,71.869043,-0.585743,71.926132,-0.642832,71.829763
3,1,0,35.0,53.1000,32.117263,20.982737,53.806886,-0.706886,54.917220,-1.817220,...,-1.036616,54.304123,-1.204123,54.271988,-1.171988,52.918067,0.181933,52.975156,0.124844,52.878787
4,3,1,35.0,8.0500,32.117263,-24.067263,9.821490,-1.771490,7.981703,0.068297,...,0.220706,7.996800,0.053200,7.964666,0.085334,7.814875,0.235125,7.871964,0.178036,7.907514
6,1,1,54.0,51.8625,32.117263,19.745237,53.806886,-1.944386,54.917220,-3.054720,...,-2.274116,54.304123,-2.441623,54.271988,-2.409488,51.972500,-0.110000,52.029589,-0.167089,51.933220
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,2,1,28.0,10.5000,32.117263,-21.617263,9.821490,0.678510,10.931824,-0.431824,...,-0.279415,10.946921,-0.446921,10.914787,-0.414787,10.764996,-0.264996,10.822085,-0.322085,10.725716
884,3,1,25.0,7.0500,32.117263,-25.067263,9.821490,-2.771490,6.940183,0.109817,...,0.262226,6.955281,0.094719,6.923146,0.126854,6.773355,0.276645,6.830444,0.219556,6.865994
887,1,0,19.0,30.0000,32.117263,-2.117263,27.853290,2.146710,28.963624,1.036376,...,0.421893,29.745614,0.254386,29.713479,0.286521,29.563688,0.436312,29.620777,0.379223,29.524408
889,1,1,26.0,30.0000,32.117263,-2.117263,27.853290,2.146710,28.963624,1.036376,...,0.421893,29.745614,0.254386,29.713479,0.286521,29.563688,0.436312,29.620777,0.379223,29.524408
890,3,1,32.0,7.7500,32.117263,-24.367263,9.821490,-2.071490,7.981703,-0.231703,...,-0.079294,7.996800,-0.246800,7.964666,-0.214666,7.814875,-0.064875,7.871964,-0.121964,7.907514

In [276]:
data=df.sample(140, random_state=42)

In [277]:
data.sort_index(inplace=True)

In [278]:
data.index

Index([  2,   7,  11,  39,  40,  53,  56,  59,  67,  72,
       ...
       827, 836, 843, 845, 852, 854, 870, 875, 885, 886],
      dtype='int64', length=140)

In [282]:
df.drop(data.index, inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_216\1702830504.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(data.index, inplace=True)

In [283]:
N=df.shape[0]
Models = 10
def Loss(yi, yipred):
    return np.square(yi-yipred)

In [284]:
N

572

In [285]:
df["f0x"]=df["Fare"].mean()
models=["f0x"]

C:\Users\DELL\AppData\Local\Temp\ipykernel_216\3010318852.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["f0x"]=df["Fare"].mean()

In [286]:
def train_model(m):
    pseudo_res=f"ri{m}"
    prev_model_out = f"f{m-1}x"
    df[pseudo_res]=df["Fare"]-df[prev_model_out]

    model = f"dtree{m}"
    model = DecisionTreeRegressor(max_depth=3)
    model.fit(df.iloc[:,1:4], df[pseudo_res])
    models.append(model)

    new_model_out = f"f{m}x"
    df[new_model_out]= df[prev_model_out]+model.predict(df.iloc[:,1:4])

In [245]:
# train_model(1)

In [287]:
def fit():
    for m in range(1,Models):
        train_model(m)

In [290]:
fit()

C:\Users\DELL\AppData\Local\Temp\ipykernel_216\3991748410.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[pseudo_res]=df["Fare"]-df[prev_model_out]
C:\Users\DELL\AppData\Local\Temp\ipykernel_216\3991748410.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[new_model_out]= df[prev_model_out]+model.predict(df.iloc[:,1:4])
C:\Users\DELL\AppData\Local\Temp\ipykernel_216\3991748410.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[pseudo_res]=df["Fare"]-df[prev_model_out]
C:\Users\DELL\AppData\Local\Temp\ipykernel_216\3991748410.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[new_model_out]= df[prev_model_out]+model.predict(df.iloc[:,1:4])
C:\Users\DELL\AppData\Local\Temp\ipykernel_216\3991748410.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[pseudo_res]=df["Fare"]-df[prev_model_out]
C:\Users\DELL\AppData\Local\Temp\ipykernel_216\3991748410.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[new_model_out]= df[prev_model_out]+model.predict(df.iloc[:,1:4])
C:\Users\DELL\AppData\Local\Temp\ipykernel_216\3991748410.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[pseudo_res]=df["Fare"]-df[prev_model_out]
C:\Users\DELL\AppData\Local\Temp\ipykernel_216\3991748410.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[new_model_out]= df[prev_model_out]+model.predict(df.iloc[:,1:4])
C:\Users\DELL\AppData\Local\Temp\ipykernel_216\3991748410.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[pseudo_res]=df["Fare"]-df[prev_model_out]
C:\Users\DELL\AppData\Local\Temp\ipykernel_216\3991748410.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[new_model_out]= df[prev_model_out]+model.predict(df.iloc[:,1:4])
C:\Users\DELL\AppData\Local\Temp\ipykernel_216\3991748410.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[pseudo_res]=df["Fare"]-df[prev_model_out]
C:\Users\DELL\AppData\Local\Temp\ipykernel_216\3991748410.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[new_model_out]= df[prev_model_out]+model.predict(df.iloc[:,1:4])
C:\Users\DELL\AppData\Local\Temp\ipykernel_216\3991748410.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[pseudo_res]=df["Fare"]-df[prev_model_out]
C:\Users\DELL\AppData\Local\Temp\ipykernel_216\3991748410.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[new_model_out]= df[prev_model_out]+model.predict(df.iloc[:,1:4])
C:\Users\DELL\AppData\Local\Temp\ipykernel_216\3991748410.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[pseudo_res]=df["Fare"]-df[prev_model_out]
C:\Users\DELL\AppData\Local\Temp\ipykernel_216\3991748410.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[new_model_out]= df[prev_model_out]+model.predict(df.iloc[:,1:4])
C:\Users\DELL\AppData\Local\Temp\ipykernel_216\3991748410.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[pseudo_res]=df["Fare"]-df[prev_model_out]
C:\Users\DELL\AppData\Local\Temp\ipykernel_216\3991748410.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[new_model_out]= df[prev_model_out]+model.predict(df.iloc[:,1:4])

In [295]:
def predict(data):
    data["f0x"]=df["Fare"].mean()
    for m in range(1,Models):
        prev_model_out = f"f{m-1}x"
          
        model = models[m]

        new_model_out = f"f{m}x"
        data[new_model_out]= data[prev_model_out]+model.predict(data.iloc[:,1:4])

In [291]:
from sklearn.metrics import r2_score
r2_score(df["Fare"], df["f9x"])

0.9997864272283833

In [296]:
predict(data)

In [297]:
r2_score(data["Fare"], data["f9x"])

0.9997910073449825

In [298]:
data

,Pclass,Sex,Age,Fare,f0x,f1x,f2x,f3x,f4x,f5x,f6x,f7x,f8x,f9x
2,3,0,26.0,7.9250,32.117263,9.82149,7.981703,7.829398,7.829294,7.996800,7.964666,7.814875,7.871964,7.907514
7,3,1,2.0,21.0750,32.117263,27.85329,28.963624,20.336616,20.336511,20.504018,20.471884,20.322092,20.379181,20.282812
11,1,0,58.0,26.5500,32.117263,27.85329,28.963624,26.556142,26.556038,26.723545,26.691410,26.541619,26.598708,26.502339
39,3,0,14.0,11.2417,32.117263,9.82149,10.931824,10.779519,10.779415,10.946921,10.914787,10.764996,10.822085,10.725716
40,3,0,40.0,9.4750,32.117263,9.82149,10.931824,10.779519,10.779415,10.946921,10.914787,10.764996,10.822085,9.537988
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
854,2,0,44.0,26.0000,32.117263,27.85329,28.963624,26.556142,26.556038,26.723545,26.691410,26.541619,26.598708,26.502339
870,3,1,26.0,7.8958,32.117263,9.82149,7.981703,7.829398,7.829294,7.996800,7.964666,7.814875,7.871964,7.907514
875,3,0,15.0,7.2250,32.117263,9.82149,6.940183,6.787878,6.787774,6.955281,6.923146,6.773355,6.830444,6.865994
885,3,0,39.0,29.1250,32.117263,27.85329,28.963624,29.578212,29.578107,29.745614,29.713479,29.563688,29.620777,29.524408
886,2,1,27.0,13.0000,32.117263,9.82149,10.931824,13.389549,13.389445,13.556951,13.524817,13.375026,13.432115,13.335746